# 开发环境 Docker Compose 配置
version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: course-management-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DEPLOY_ENV=${DEPLOY_ENV:-dev}
      - VITE_HMR_HOST=0.0.0.0
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
      - /app/node_modules
    restart: unless-stopped
    networks:
      - course-management-dev-network
    command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  course-management-dev-network:
    driver: bridge
